### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by Matsuri247** [Jiawei-Yang/Denoising-ViT#7]
The instruction is insufficient

**Comment by Jiawei-Yang** [comment]
Hi, thanks again for your interest in our work. We do plan to update our codebase soon with more detailed instructions when we have the bandwidth (at least after recent rebuttal and submission deadlines). To a large extent, it is still self-contained and runnable, as some other folks have successfully reproduced the results.

Feel free to leave comments for issues you encounter and I'll try to get back soon.
